application:
  subdomain: qrding
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://qrding:3000/
services:
  qrding:
    # upstream: ghcr.io/rishikanthc/qrding:v0.1.2
    image: registry.lazycat.cloud/czyt/rishikanthc/qrding:04a76d53ce6181d6
