package: lazycat.community.app.qrding
version: 0.1.2
name: QRding
description: simple self-hosted QR code generator
homepage: https://github.com/rishikanthc/qrding
author: rishikanthc
license: MIT
locales:
  en:
    name: QRding
    description: simple self-hosted QR code generator
  zh-CN:
    name: QRding
    description: 简单的自托管二维码生成器
min_os_version: 1.5.0
